//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.27 at 07:35:32 AM CET 
//


package com.adobe.ns.xap._1_0.rights;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.adobe.ns.xap._1_0.rights package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Owner_QNAME = new QName("http://ns.adobe.com/xap/1.0/rights/", "Owner");
    private final static QName _Marked_QNAME = new QName("http://ns.adobe.com/xap/1.0/rights/", "Marked");
    private final static QName _UsageTerms_QNAME = new QName("http://ns.adobe.com/xap/1.0/rights/", "UsageTerms");
    private final static QName _WebStatement_QNAME = new QName("http://ns.adobe.com/xap/1.0/rights/", "WebStatement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.adobe.ns.xap._1_0.rights
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.adobe.com/xap/1.0/rights/", name = "Owner")
    public JAXBElement<String> createOwner(String value) {
        return new JAXBElement<String>(_Owner_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.adobe.com/xap/1.0/rights/", name = "Marked")
    public JAXBElement<Boolean> createMarked(Boolean value) {
        return new JAXBElement<Boolean>(_Marked_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.adobe.com/xap/1.0/rights/", name = "UsageTerms")
    public JAXBElement<String> createUsageTerms(String value) {
        return new JAXBElement<String>(_UsageTerms_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.adobe.com/xap/1.0/rights/", name = "WebStatement")
    public JAXBElement<String> createWebStatement(String value) {
        return new JAXBElement<String>(_WebStatement_QNAME, String.class, null, value);
    }

}
