//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.27 at 07:35:32 AM CET 
//


package https.lod_academy.cvma.ns.xmp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cvmaEntityRole.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cvmaEntityRole">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Stifter"/>
 *     &lt;enumeration value="Entwerfer"/>
 *     &lt;enumeration value="Werkstatt"/>
 *     &lt;enumeration value="Restaurator"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cvmaEntityRole")
@XmlEnum
public enum CvmaEntityRole {

    @XmlEnumValue("Stifter")
    STIFTER("Stifter"),
    @XmlEnumValue("Entwerfer")
    ENTWERFER("Entwerfer"),
    @XmlEnumValue("Werkstatt")
    WERKSTATT("Werkstatt"),
    @XmlEnumValue("Restaurator")
    RESTAURATOR("Restaurator");
    private final String value;

    CvmaEntityRole(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CvmaEntityRole fromValue(String v) {
        for (CvmaEntityRole c: CvmaEntityRole.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
