//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.27 at 07:35:32 AM CET 
//


package https.lod_academy.cvma.ns.xmp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cvmaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cvmaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Glasmalerei"/>
 *     &lt;enumeration value="Buchmalerei"/>
 *     &lt;enumeration value="Tafelmalerei"/>
 *     &lt;enumeration value="Wandmalerei"/>
 *     &lt;enumeration value="Architektur"/>
 *     &lt;enumeration value="Skulptur"/>
 *     &lt;enumeration value="Zeichnung"/>
 *     &lt;enumeration value="Druckgraphik"/>
 *     &lt;enumeration value="Textilwerk"/>
 *     &lt;enumeration value="Bauornamentik"/>
 *     &lt;enumeration value="Metallwerk"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cvmaType")
@XmlEnum
public enum CvmaType {

    @XmlEnumValue("Glasmalerei")
    GLASMALEREI("Glasmalerei"),
    @XmlEnumValue("Buchmalerei")
    BUCHMALEREI("Buchmalerei"),
    @XmlEnumValue("Tafelmalerei")
    TAFELMALEREI("Tafelmalerei"),
    @XmlEnumValue("Wandmalerei")
    WANDMALEREI("Wandmalerei"),
    @XmlEnumValue("Architektur")
    ARCHITEKTUR("Architektur"),
    @XmlEnumValue("Skulptur")
    SKULPTUR("Skulptur"),
    @XmlEnumValue("Zeichnung")
    ZEICHNUNG("Zeichnung"),
    @XmlEnumValue("Druckgraphik")
    DRUCKGRAPHIK("Druckgraphik"),
    @XmlEnumValue("Textilwerk")
    TEXTILWERK("Textilwerk"),
    @XmlEnumValue("Bauornamentik")
    BAUORNAMENTIK("Bauornamentik"),
    @XmlEnumValue("Metallwerk")
    METALLWERK("Metallwerk");
    private final String value;

    CvmaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CvmaType fromValue(String v) {
        for (CvmaType c: CvmaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
