//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.27 at 07:35:32 AM CET 
//


package https.lod_academy.cvma.ns.xmp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cvmaPhotographicContext.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cvmaPhotographicContext">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="in situ"/>
 *     &lt;enumeration value="ausgebaut"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cvmaPhotographicContext")
@XmlEnum
public enum CvmaPhotographicContext {

    @XmlEnumValue("in situ")
    IN_SITU("in situ"),
    @XmlEnumValue("ausgebaut")
    AUSGEBAUT("ausgebaut");
    private final String value;

    CvmaPhotographicContext(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CvmaPhotographicContext fromValue(String v) {
        for (CvmaPhotographicContext c: CvmaPhotographicContext.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
