//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.27 at 07:35:32 AM CET 
//


package https.lod_academy.cvma.ns.xmp;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.purl.dc.elements._1.SimpleLiteral;


/**
 * Metadata 4 applied sciences. (MASi)
 * 
 * <p>Java class for cvmaRootType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cvmaRootType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}title" minOccurs="0"/>
 *         &lt;element name="Type" type="{https://lod.academy/cvma/ns/xmp/}cvmaType" maxOccurs="11" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}relation" minOccurs="0"/>
 *         &lt;element name="Volume" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Figure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}identifier" minOccurs="0"/>
 *         &lt;element name="PhotographicType" type="{https://lod.academy/cvma/ns/xmp/}cvmaPhotographicType" minOccurs="0"/>
 *         &lt;element ref="{http://iptc.org/std/Iptc4xmpExt/2008-02-29/}DigitalSourceType" minOccurs="0"/>
 *         &lt;element name="PhotographicContext" type="{https://lod.academy/cvma/ns/xmp/}cvmaPhotographicContext" minOccurs="0"/>
 *         &lt;element ref="{http://ns.adobe.com/xap/1.0/}CreateDate" minOccurs="0"/>
 *         &lt;element ref="{http://iptc.org/std/Iptc4xmpExt/2008-02-29/}WorldRegion" minOccurs="0"/>
 *         &lt;element ref="{http://iptc.org/std/Iptc4xmpExt/2008-02-29/}CountryName" minOccurs="0"/>
 *         &lt;element ref="{http://iptc.org/std/Iptc4xmpExt/2008-02-29/}ProvinceState" minOccurs="0"/>
 *         &lt;element ref="{http://iptc.org/std/Iptc4xmpExt/2008-02-29/}City" minOccurs="0"/>
 *         &lt;element ref="{http://iptc.org/std/Iptc4xmpExt/2008-02-29/}Sublocation" minOccurs="0"/>
 *         &lt;element name="PartOfBuilding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GPSLatitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GPSLongitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://iptc.org/std/Iptc4xmpExt/2008-02-29/}LocationId" minOccurs="0"/>
 *         &lt;element name="Direction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Pane" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Row" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FormerLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FormerLocationIds" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ObjectHeight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ObjectWidth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ObjectDiameter" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element ref="{http://iptc.org/std/Iptc4xmpExt/2008-02-29/}AOCircaDateCreated" minOccurs="0"/>
 *         &lt;element name="AgeDeterminationStart" type="{https://lod.academy/cvma/ns/xmp/}severalDates" minOccurs="0"/>
 *         &lt;element name="AgeDeterminationEnd" type="{https://lod.academy/cvma/ns/xmp/}severalDates" minOccurs="0"/>
 *         &lt;element name="RestorationHistory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EntityName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EntityIdentifier" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EntityRole" type="{https://lod.academy/cvma/ns/xmp/}cvmaEntityRole" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IconclassNotation" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IconclassDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://ns.adobe.com/xap/1.0/rights/}Marked" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}creator" minOccurs="0"/>
 *         &lt;element ref="{http://ns.adobe.com/xap/1.0/rights/}Owner" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}publisher" minOccurs="0"/>
 *         &lt;element ref="{http://ns.adobe.com/photoshop/1.0/}Credit" minOccurs="0"/>
 *         &lt;element ref="{http://ns.adobe.com/xap/1.0/rights/}UsageTerms" minOccurs="0"/>
 *         &lt;element ref="{http://ns.adobe.com/xap/1.0/rights/}WebStatement" minOccurs="0"/>
 *         &lt;element name="PublishingStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{http://ns.adobe.com/photoshop/1.0/}Instructions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cvmaRootType", propOrder = {
    "title",
    "type",
    "relation",
    "volume",
    "figure",
    "identifier",
    "photographicType",
    "digitalSourceType",
    "photographicContext",
    "createDate",
    "worldRegion",
    "countryName",
    "provinceState",
    "city",
    "sublocation",
    "partOfBuilding",
    "gpsLatitude",
    "gpsLongitude",
    "locationId",
    "direction",
    "pane",
    "row",
    "column",
    "formerLocation",
    "formerLocationIds",
    "objectHeight",
    "objectWidth",
    "objectDiameter",
    "aoCircaDateCreated",
    "ageDeterminationStart",
    "ageDeterminationEnd",
    "restorationHistory",
    "entityName",
    "entityIdentifier",
    "entityRole",
    "iconclassNotation",
    "iconclassDescription",
    "marked",
    "creator",
    "owner",
    "publisher",
    "credit",
    "usageTerms",
    "webStatement",
    "publishingStatus",
    "instructions"
})
public class CvmaRootType {

    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/")
    protected SimpleLiteral title;
    @XmlElement(name = "Type")
    @XmlSchemaType(name = "string")
    protected List<CvmaType> type;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/")
    protected SimpleLiteral relation;
    @XmlElement(name = "Volume")
    protected String volume;
    @XmlElement(name = "Figure")
    protected String figure;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/")
    protected SimpleLiteral identifier;
    @XmlElement(name = "PhotographicType")
    @XmlSchemaType(name = "string")
    protected CvmaPhotographicType photographicType;
    @XmlElement(name = "DigitalSourceType", namespace = "http://iptc.org/std/Iptc4xmpExt/2008-02-29/")
    protected String digitalSourceType;
    @XmlElement(name = "PhotographicContext")
    @XmlSchemaType(name = "string")
    protected CvmaPhotographicContext photographicContext;
    @XmlElement(name = "CreateDate", namespace = "http://ns.adobe.com/xap/1.0/")
    protected String createDate;
    @XmlElement(name = "WorldRegion", namespace = "http://iptc.org/std/Iptc4xmpExt/2008-02-29/")
    protected String worldRegion;
    @XmlElement(name = "CountryName", namespace = "http://iptc.org/std/Iptc4xmpExt/2008-02-29/")
    protected String countryName;
    @XmlElement(name = "ProvinceState", namespace = "http://iptc.org/std/Iptc4xmpExt/2008-02-29/")
    protected String provinceState;
    @XmlElement(name = "City", namespace = "http://iptc.org/std/Iptc4xmpExt/2008-02-29/")
    protected String city;
    @XmlElement(name = "Sublocation", namespace = "http://iptc.org/std/Iptc4xmpExt/2008-02-29/")
    protected String sublocation;
    @XmlElement(name = "PartOfBuilding")
    protected String partOfBuilding;
    @XmlElement(name = "GPSLatitude")
    protected String gpsLatitude;
    @XmlElement(name = "GPSLongitude")
    protected String gpsLongitude;
    @XmlElement(name = "LocationId", namespace = "http://iptc.org/std/Iptc4xmpExt/2008-02-29/")
    @XmlSchemaType(name = "anyURI")
    protected String locationId;
    @XmlElement(name = "Direction")
    protected String direction;
    @XmlElement(name = "Pane")
    protected String pane;
    @XmlElement(name = "Row")
    protected String row;
    @XmlElement(name = "Column")
    protected String column;
    @XmlElement(name = "FormerLocation")
    protected String formerLocation;
    @XmlElement(name = "FormerLocationIds")
    @XmlSchemaType(name = "anyURI")
    protected List<String> formerLocationIds;
    @XmlElement(name = "ObjectHeight")
    protected BigDecimal objectHeight;
    @XmlElement(name = "ObjectWidth")
    protected BigDecimal objectWidth;
    @XmlElement(name = "ObjectDiameter")
    protected BigDecimal objectDiameter;
    @XmlElement(name = "AOCircaDateCreated", namespace = "http://iptc.org/std/Iptc4xmpExt/2008-02-29/")
    protected String aoCircaDateCreated;
    @XmlElement(name = "AgeDeterminationStart")
    protected String ageDeterminationStart;
    @XmlElement(name = "AgeDeterminationEnd")
    protected String ageDeterminationEnd;
    @XmlElement(name = "RestorationHistory")
    protected String restorationHistory;
    @XmlElement(name = "EntityName")
    protected List<String> entityName;
    @XmlElement(name = "EntityIdentifier")
    @XmlSchemaType(name = "anyURI")
    protected List<String> entityIdentifier;
    @XmlElement(name = "EntityRole")
    @XmlSchemaType(name = "string")
    protected List<CvmaEntityRole> entityRole;
    @XmlElement(name = "IconclassNotation")
    protected List<String> iconclassNotation;
    @XmlElement(name = "IconclassDescription")
    protected String iconclassDescription;
    @XmlElement(name = "Marked", namespace = "http://ns.adobe.com/xap/1.0/rights/")
    protected Boolean marked;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/")
    protected SimpleLiteral creator;
    @XmlElement(name = "Owner", namespace = "http://ns.adobe.com/xap/1.0/rights/")
    protected String owner;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/")
    protected SimpleLiteral publisher;
    @XmlElement(name = "Credit", namespace = "http://ns.adobe.com/photoshop/1.0/")
    protected String credit;
    @XmlElement(name = "UsageTerms", namespace = "http://ns.adobe.com/xap/1.0/rights/")
    protected String usageTerms;
    @XmlElement(name = "WebStatement", namespace = "http://ns.adobe.com/xap/1.0/rights/")
    @XmlSchemaType(name = "anyURI")
    protected String webStatement;
    @XmlElement(name = "PublishingStatus")
    protected Boolean publishingStatus;
    @XmlElement(name = "Instructions", namespace = "http://ns.adobe.com/photoshop/1.0/")
    protected String instructions;

    /**
     * Beschreibender Titel des abgebildeten Werks bzw. der abgebildeten Scheibe.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setTitle(SimpleLiteral value) {
        this.title = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CvmaType }
     * 
     * 
     */
    public List<CvmaType> getType() {
        if (type == null) {
            type = new ArrayList<CvmaType>();
        }
        return this.type;
    }

    /**
     * A list of related resources.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getRelation() {
        return relation;
    }

    /**
     * Sets the value of the relation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setRelation(SimpleLiteral value) {
        this.relation = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolume(String value) {
        this.volume = value;
    }

    /**
     * Gets the value of the figure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFigure() {
        return figure;
    }

    /**
     * Sets the value of the figure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFigure(String value) {
        this.figure = value;
    }

    /**
     * An unambiguous reference to the resource within a given context. Recommended best practice is to identify the resource by means of a text conforming to a formal identification system.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setIdentifier(SimpleLiteral value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the photographicType property.
     * 
     * @return
     *     possible object is
     *     {@link CvmaPhotographicType }
     *     
     */
    public CvmaPhotographicType getPhotographicType() {
        return photographicType;
    }

    /**
     * Sets the value of the photographicType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CvmaPhotographicType }
     *     
     */
    public void setPhotographicType(CvmaPhotographicType value) {
        this.photographicType = value;
    }

    /**
     * Herstellungsmethode der fotografischen Aufnahme.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigitalSourceType() {
        return digitalSourceType;
    }

    /**
     * Sets the value of the digitalSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigitalSourceType(String value) {
        this.digitalSourceType = value;
    }

    /**
     * Gets the value of the photographicContext property.
     * 
     * @return
     *     possible object is
     *     {@link CvmaPhotographicContext }
     *     
     */
    public CvmaPhotographicContext getPhotographicContext() {
        return photographicContext;
    }

    /**
     * Sets the value of the photographicContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link CvmaPhotographicContext }
     *     
     */
    public void setPhotographicContext(CvmaPhotographicContext value) {
        this.photographicContext = value;
    }

    /**
     * The date and time the resource was created. For a digital file, this need not match a file-system creation time.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateDate(String value) {
        this.createDate = value;
    }

    /**
     * The name of a world region of a location. This element is at the first (topI) level of a top-down geographical hierarchy.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorldRegion() {
        return worldRegion;
    }

    /**
     * Sets the value of the worldRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorldRegion(String value) {
        this.worldRegion = value;
    }

    /**
     * Name eines Staats/eines Landes. Dieses Element ist auf der zweiten Ebene einer geographischen Hierarchie angesiedelt.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the value of the countryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryName(String value) {
        this.countryName = value;
    }

    /**
     * The name of a subregion of a country - a province or state - of a location. This element is at the third level of a top-down geographical hierarchy.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinceState() {
        return provinceState;
    }

    /**
     * Sets the value of the provinceState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinceState(String value) {
        this.provinceState = value;
    }

    /**
     * Für die Schreibweise der deutschen Ortsnamen wird DEHIO verwendet. Historische Ortsnamen werden beibehalten, auf den Zusatz Bad wird verzichtet. Ausländische Ortsnamen werden in der offiziellen deutschen Schreibweise verwendet.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Name of a sublocation. This sublocation name could either be the name of a sublocation to a city or the name of a well known location or (natural) monument outside a city. In the sense of a sublocation to a city this element is at the fifth level of a top-down geographical hierarchy.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSublocation() {
        return sublocation;
    }

    /**
     * Sets the value of the sublocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSublocation(String value) {
        this.sublocation = value;
    }

    /**
     * Gets the value of the partOfBuilding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartOfBuilding() {
        return partOfBuilding;
    }

    /**
     * Sets the value of the partOfBuilding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartOfBuilding(String value) {
        this.partOfBuilding = value;
    }

    /**
     * Gets the value of the gpsLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGPSLatitude() {
        return gpsLatitude;
    }

    /**
     * Sets the value of the gpsLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGPSLatitude(String value) {
        this.gpsLatitude = value;
    }

    /**
     * Gets the value of the gpsLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGPSLongitude() {
        return gpsLongitude;
    }

    /**
     * Sets the value of the gpsLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGPSLongitude(String value) {
        this.gpsLongitude = value;
    }

    /**
     * Globally unique identifier of the location.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * Sets the value of the locationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationId(String value) {
        this.locationId = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the pane property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPane() {
        return pane;
    }

    /**
     * Sets the value of the pane property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPane(String value) {
        this.pane = value;
    }

    /**
     * Gets the value of the row property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRow() {
        return row;
    }

    /**
     * Sets the value of the row property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRow(String value) {
        this.row = value;
    }

    /**
     * Gets the value of the column property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumn(String value) {
        this.column = value;
    }

    /**
     * Gets the value of the formerLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormerLocation() {
        return formerLocation;
    }

    /**
     * Sets the value of the formerLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormerLocation(String value) {
        this.formerLocation = value;
    }

    /**
     * Gets the value of the formerLocationIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formerLocationIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormerLocationIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFormerLocationIds() {
        if (formerLocationIds == null) {
            formerLocationIds = new ArrayList<String>();
        }
        return this.formerLocationIds;
    }

    /**
     * Gets the value of the objectHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getObjectHeight() {
        return objectHeight;
    }

    /**
     * Sets the value of the objectHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setObjectHeight(BigDecimal value) {
        this.objectHeight = value;
    }

    /**
     * Gets the value of the objectWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getObjectWidth() {
        return objectWidth;
    }

    /**
     * Sets the value of the objectWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setObjectWidth(BigDecimal value) {
        this.objectWidth = value;
    }

    /**
     * Gets the value of the objectDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getObjectDiameter() {
        return objectDiameter;
    }

    /**
     * Sets the value of the objectDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setObjectDiameter(BigDecimal value) {
        this.objectDiameter = value;
    }

    /**
     * Approximate date or range of dates associated with the creation and production of an artwork or object or its components.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAOCircaDateCreated() {
        return aoCircaDateCreated;
    }

    /**
     * Sets the value of the aoCircaDateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAOCircaDateCreated(String value) {
        this.aoCircaDateCreated = value;
    }

    /**
     * Gets the value of the ageDeterminationStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeDeterminationStart() {
        return ageDeterminationStart;
    }

    /**
     * Sets the value of the ageDeterminationStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeDeterminationStart(String value) {
        this.ageDeterminationStart = value;
    }

    /**
     * Gets the value of the ageDeterminationEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeDeterminationEnd() {
        return ageDeterminationEnd;
    }

    /**
     * Sets the value of the ageDeterminationEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeDeterminationEnd(String value) {
        this.ageDeterminationEnd = value;
    }

    /**
     * Gets the value of the restorationHistory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestorationHistory() {
        return restorationHistory;
    }

    /**
     * Sets the value of the restorationHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestorationHistory(String value) {
        this.restorationHistory = value;
    }

    /**
     * Gets the value of the entityName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEntityName() {
        if (entityName == null) {
            entityName = new ArrayList<String>();
        }
        return this.entityName;
    }

    /**
     * Gets the value of the entityIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEntityIdentifier() {
        if (entityIdentifier == null) {
            entityIdentifier = new ArrayList<String>();
        }
        return this.entityIdentifier;
    }

    /**
     * Gets the value of the entityRole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityRole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CvmaEntityRole }
     * 
     * 
     */
    public List<CvmaEntityRole> getEntityRole() {
        if (entityRole == null) {
            entityRole = new ArrayList<CvmaEntityRole>();
        }
        return this.entityRole;
    }

    /**
     * Gets the value of the iconclassNotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iconclassNotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIconclassNotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIconclassNotation() {
        if (iconclassNotation == null) {
            iconclassNotation = new ArrayList<String>();
        }
        return this.iconclassNotation;
    }

    /**
     * Gets the value of the iconclassDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconclassDescription() {
        return iconclassDescription;
    }

    /**
     * Sets the value of the iconclassDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconclassDescription(String value) {
        this.iconclassDescription = value;
    }

    /**
     * When true, indicates that this is a rights-managed resource. When false, indicates that this is a public-domain resource. Omit if the state is unknown.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMarked() {
        return marked;
    }

    /**
     * Sets the value of the marked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMarked(Boolean value) {
        this.marked = value;
    }

    /**
     * An entity primarily responsible for making the resource.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setCreator(SimpleLiteral value) {
        this.creator = value;
    }

    /**
     * A list of legal owners of the resource.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * A list of publishers.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setPublisher(SimpleLiteral value) {
        this.publisher = value;
    }

    /**
     * The credit to person(s) and/or organisation(s) required by the supplier of the item to be used when published.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredit(String value) {
        this.credit = value;
    }

    /**
     * A collection of text instructions on how a resource can be legally used, given in a variety of languages.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsageTerms() {
        return usageTerms;
    }

    /**
     * Sets the value of the usageTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsageTerms(String value) {
        this.usageTerms = value;
    }

    /**
     * A Web URL for a statement of the ownership and usage rights for this resource.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebStatement() {
        return webStatement;
    }

    /**
     * Sets the value of the webStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebStatement(String value) {
        this.webStatement = value;
    }

    /**
     * Gets the value of the publishingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPublishingStatus() {
        return publishingStatus;
    }

    /**
     * Sets the value of the publishingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublishingStatus(Boolean value) {
        this.publishingStatus = value;
    }

    /**
     * Any of a number of instructions from the provider or creator to the receiver of the item.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructions() {
        return instructions;
    }

    /**
     * Sets the value of the instructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructions(String value) {
        this.instructions = value;
    }

}
