//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.27 at 07:35:32 AM CET 
//


package https.lod_academy.cvma.ns.xmp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.lod_academy.cvma.ns.xmp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cvma_QNAME = new QName("https://lod.academy/cvma/ns/xmp/", "cvma");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.lod_academy.cvma.ns.xmp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CvmaRootType }
     * 
     */
    public CvmaRootType createCvmaRootType() {
        return new CvmaRootType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CvmaRootType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://lod.academy/cvma/ns/xmp/", name = "cvma")
    public JAXBElement<CvmaRootType> createCvma(CvmaRootType value) {
        return new JAXBElement<CvmaRootType>(_Cvma_QNAME, CvmaRootType.class, null, value);
    }

}
